use oldNew;

insert into `user` values (default, 'admin@mail.ua', 'Ivanov', 'Ivanovich', 'adminAdmin', 'FirstAdmin');
insert into `user` values (default , 'dispatcher1@mail.ua', 'Alex', 'Alexovich', 'dispDisp1', 'FirstDispatcher');
insert into `user` values (default , 'dispatcher2@mail.ua',  'Kirill', 'Kirillovich', 'dispDisp2', 'SecondDispatcher');
insert into `user` values (default , 'driver1@mail.ua',  'Grish', 'UnTuchable','driverDriver1', 'FirstDriver');
insert into `user` values (default , 'driver2@mail.ua',  'Tolya', 'Pull', 'driverDriver2', 'SecondDriver');
insert into `user` values (default , 'driver3@mail.ua',  'Vasya', 'Forsash', 'driverDriver3', 'ThirdDriver');

insert into user_role values (1, 'ADMIN');
insert into user_role values (2, 'DISPATCHER');
insert into user_role values (3, 'DISPATCHER');
insert into user_role values (4, 'DRIVER');
insert into user_role values (5, 'DRIVER');
insert into user_role values (6, 'DRIVER');

insert into auto values (default, 30, true, 2.3, '/media/auto/67299a6s-1920.jpg',  'Audi', false,  1.8, 1);
insert into auto values (default, 40, true, 2.5, '/media/auto/67299a6s-1920.jpg',  'Chevrolet', false,  2.2,   2);
insert into auto values (default, 20, true,  2.1, '/media/auto/67299a6s-1920.jpg', 'Chevrolet', false, 2.3,   null);
insert into auto values (default, 35, false, 1.6, '/media/auto/67299a6s-1920.jpg', 'Ford', false, 2.4,   null);
insert into auto values (default, 30,  true,  2.3, '/media/auto/67299a6s-1920.jpg', 'Audi', false, 1.8, null);
insert into auto values (default, 50, false, 2.6, '/media/auto/67299a6s-1920.jpg', 'Chevrolet',  false, 2.5,   null);
insert into auto values (default, 25, false, 1.5, '/media/auto/67299a6s-1920.jpg', 'Ford', false,  2.2,    null);

insert into auto values (default, 30, true, 2.1, '/media/auto/67299a6s-1920.jpg', 'Ford',  false,  2.0,   null);
insert into auto values (default, 25, true, 1.8, '/media/auto/67299a6s-1920.jpg', 'Audi', false,  2.5,   null);
insert into auto values (default, 20, true, 2.2, '/media/auto/67299a6s-1920.jpg', 'Mazda', false,   2.2,   null);
insert into auto values (default, 40, true, 1.9, '/media/auto/67299a6s-1920.jpg', 'Chipirka', false,   2.3,   null);
insert into auto values (default, 45, true, 2.3, '/media/auto/67299a6s-1920.jpg', 'Chevrolet', false,  2.5,   null);
insert into auto values (default, 45, true, 2.3, '/media/auto/67299a6s-1920.jpg', 'Chevrolet', false,  2.5,   null);

insert into journey values (default, now(), null,'Kharkiv', null,  'OPENED', 'Kiev' , 4, null);
insert into journey values (default, now(), null, 'Odessa', null, 'PROCESS', 'Lviv', 5, 5);
insert into journey values (default, now(), null, 'Kiev', null, 'CLOSED',  'Minsk', 6, null);
insert into journey values (default, now(), null, 'Kharkiv', null, 'OPENED',  'Kiev',6, null);
insert into journey values (default, now(), null, 'Kiev', null, 'OPENED', 'Minsk' ,4, null);
insert into journey values (default, now(), null, 'Odessa', null, 'PROCESS', 'Lviv', 5, 4);
insert into journey values (default, now(), null, 'Kharkiv', null, 'CLOSED', 'Kiev',6, null);
insert into journey values (default, now(), null, 'Kiev', null, 'CANCELED',  'Minsk',6, null);
insert into journey values (default, now(), null, 'Odessa', null, 'OPENED',  'Lviv',4, null);
insert into journey values (default, now(), null,'Minsk', null, 'PROCESS',  'Kiev', 5, 6);
insert into journey values (default, now(), null,'Kharkiv', null, 'CLOSED',  'Kiev',6, null);
insert into journey values (default, now(), null, 'Minsk', null, 'CANCELED', 'Kiev',6, null);
insert into journey values (default, now(), null,'Kiev', null, 'OPENED', 'Minsk' ,4, null);
insert into journey values (default, now(), null, 'Alchevsk', null, 'PROCESS', 'Odessa', 5, 4);
insert into journey values (default, now(), null, 'Kharkiv', null, 'CLOSED', 'Kiev',6, null);
insert into journey values (default, now(), null,'Odessa', null, 'CANCELED', 'Lviv',6, null);
insert into journey values (default, now(), null,'Kiev', null, 'OPENED',  'Minsk' ,4, null);
insert into journey values (default, now(), null, 'Kharkiv', null, 'PROCESS', 'Kiev', 5, 6);
insert into journey values (default, now(), null, 'Minsk', null, 'CLOSED',  'Kiev',6, null);
insert into journey values (default, now(), null, 'Kiev', null, 'CANCELED',  'Minsk',6, null);
insert into journey values (default, now(), null, 'Odessa', null, 'OPENED', 'Lviv',4, null);
insert into journey values (default, now(), null, 'Minsk', null, 'PROCESS', 'Kiev', 5, 5);
insert into journey values (default, now(), null, 'Kharkiv', null, 'CLOSED', 'Kiev',6, null);
insert into journey values (default, now(), null,'Odessa', null, 'OPENED', 'Lviv',4, null);

insert into `request` values (default, 32, now(), 'Kharkiv', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something ', true,   'Kiev', 1.8,   4);
insert into `request` values (default, 32,  now(), 'Dnipro', 1.8, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',false,  'Odessa',  2.5,  5 );
insert into `request` values (default, 32,  now(), 'Karpats', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Kharkiv',  1.8,    5);
insert into `request` values (default, 32, now(), 'Odessa', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Dnipro',  1.8,   6);
insert into `request` values (default, 32, now(), 'Kharkiv', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something ', true,   'Kiev', 1.8,   4);
insert into `request` values (default, 32,  now(), 'Dnipro', 1.8, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',false,  'Odessa',  2.5,  5 );
insert into `request` values (default, 32,  now(), 'Karpats', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Kharkiv',  1.8,    5);
insert into `request` values (default, 32, now(), 'Odessa', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Dnipro',  1.8,   6);
insert into `request` values (default, 32, now(), 'Kharkiv', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something ', true,   'Kiev', 1.8,   4);
insert into `request` values (default, 32,  now(), 'Dnipro', 1.8, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',false,  'Odessa',  2.5,  5 );
insert into `request` values (default, 32,  now(), 'Karpats', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Kharkiv',  1.8,    5);
insert into `request` values (default, 32, now(), 'Odessa', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Dnipro',  1.8,   6);
insert into `request` values (default, 32, now(), 'Kharkiv', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something ', true,   'Kiev', 1.8,   4);
insert into `request` values (default, 32,  now(), 'Dnipro', 1.8, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',false,  'Odessa',  2.5,  5 );
insert into `request` values (default, 32,  now(), 'Karpats', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Kharkiv',  1.8,    5);
insert into `request` values (default, 32, now(), 'Odessa', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Dnipro',  1.8,   6);
insert into `request` values (default, 32, now(), 'Kharkiv', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something ', true,   'Kiev', 1.8,   4);
insert into `request` values (default, 32,  now(), 'Dnipro', 1.8, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',false,  'Odessa',  2.5,  5 );
insert into `request` values (default, 32,  now(), 'Karpats', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Kharkiv',  1.8,    5);
insert into `request` values (default, 32, now(), 'Odessa', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Dnipro',  1.8,   6);
insert into `request` values (default, 32, now(), 'Kharkiv', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something ', true,   'Kiev', 1.8,   4);
insert into `request` values (default, 32,  now(), 'Dnipro', 1.8, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',false,  'Odessa',  2.5,  5 );
insert into `request` values (default, 32,  now(), 'Karpats', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Kharkiv',  1.8,    5);
insert into `request` values (default, 32, now(), 'Odessa', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Dnipro',  1.8,   6);
insert into `request` values (default, 32, now(), 'Kharkiv', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something ', true,   'Kiev', 1.8,   4);
insert into `request` values (default, 32,  now(), 'Dnipro', 1.8, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',false,  'Odessa',  2.5,  5 );
insert into `request` values (default, 32,  now(), 'Karpats', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Kharkiv',  1.8,    5);
insert into `request` values (default, 32, now(), 'Odessa', 2.5, 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 'Dnipro',  1.8,   6);

insert into `rejection` values (default, now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',   true , 6, 4);
insert into `rejection` values (default,  now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 10, 4);
insert into `rejection` values (default, now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 12, 4);
insert into `rejection` values (default, now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',   true, 6, 5);
insert into `rejection` values (default, now(),  'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 10, 5);
insert into `rejection` values (default,  now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 12, 5);
insert into `rejection` values (default, now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',  true, 6, 5);
insert into `rejection` values (default, now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 10, 6);
insert into `rejection` values (default, now(),'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',  true, 12, 6);
insert into `rejection` values (default, now(),'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',   false, 6, 4);
insert into `rejection` values (default, now(),'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',  false, 10, 4);
insert into `rejection` values (default,  now(),'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 12, 4);
insert into `rejection` values (default, now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',  true, 6, 5);
insert into `rejection` values (default,  now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 10, 5);
insert into `rejection` values (default, now(),  'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something', false, 12, 5);
insert into `rejection` values (default, now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',  true, 6, 5);
insert into `rejection` values (default, now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',  false, 10, 6);
insert into `rejection` values (default, now(), 'Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something Something',  false, 12, 6);